{
 "title": "Domains monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2h",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domínios monitorados",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT count(*) FROM domains" }
   ]
  },
  {
   "title": "Não suportados",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM domains WHERE name LIKE '%UNSUPORTED%'"
    }
   ]
  },
  {
   "title": "Inválidos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM domains WHERE name LIKE '%INVALID%'"
    }
   ]
  },
  {
   "title": "Taxa de domínios por fornecedor",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*), providers.name as provider FROM domains INNER JOIN providers ON providers.id = domains.provider_id GROUP BY providers.name"
    }
   ]
  },
  {
   "title": "Relação de domínios por marca",
   "type": "piechart",
   "description": "Valores aproximados utilizando padrão de nomes",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as americanas FROM domains WHERE name LIKE '%americana%' OR name LIKE '%acom'\n"
    },
    {
     "rawSql": "SELECT count(*) as submarino FROM domains WHERE name LIKE '%sub%' \n"
    },
    {
     "rawSql": "SELECT count(*) as soub FROM domains WHERE name LIKE '%soub%' \n"
    },
    {
     "rawSql": "SELECT count(*) as shop FROM domains WHERE name LIKE '%shop%' \n"
    },
    {
     "rawSql": "SELECT count(*) as b2w FROM domains WHERE name LIKE '%b2w%' "
    },
    {
     "rawSql": "SELECT count(*) as ame FROM domains WHERE name NOT LIKE '%amer%' AND name LIKE '%ame%'"
    },
    {
     "rawSql": "SELECT count(*) as outros FROM domains WHERE \n  name NOT LIKE '%americanas%' AND \n  name NOT LIKE '%ame%' AND \n  name NOT LIKE '%b2w%' AND\n  name NOT LIKE '%shop%' AND\n  name NOT LIKE '%soub%' AND\n  name NOT LIKE '%sub%'\n  \n  "
    }
   ]
  },
  {
   "title": "Domínios vencidos",
   "type": "stat",
   "description": "Domínios que expiraram no mês anterior onde não foi identificada a renovação, por permanência da data de expiração antiga",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM domains \n\tINNER JOIN \n\t  providers on providers.id = domains.provider_id\n\t  \n  WHERE \n\t-- DAY 1 OF THIS MONTH\n\t\texpiration_date >= CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 - INTERVAL '1 month' as DATE) as TEXT)\n\tAND \n\t-- DAY 1 OF NEXT MONTH\n\t\texpiration_date < CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 as TEXT)\n"
    }
   ]
  },
  {
   "title": "Nome dos domínios que estão vencidos",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT domains.name, providers.name as Provedor FROM domains \n\nINNER JOIN \n  providers on providers.id = domains.provider_id\n\nWHERE \n\t-- DAY 1 OF THIS MONTH\n\t\texpiration_date >= CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 - INTERVAL '1 month' as DATE) as TEXT)\n\tAND \n\t-- DAY 1 OF NEXT MONTH\n\t\texpiration_date < CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 as TEXT)\n\t\t\n\tORDER BY expiration_date"
    }
   ]
  },
  { "title": "Domínios expirando", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Domínios expirando neste mês",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM domains WHERE \n\t-- DAY 1 OF THIS MONTH\n\t\texpiration_date >= CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 as TEXT)\n\tAND \n\t-- DAY 1 OF NEXT MONTH\n\t\texpiration_date < CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 + INTERVAL '1 month' as DATE) as TEXT)\n"
    }
   ]
  },
  {
   "title": "Domínios expirando nesse mês (por fornecedor)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*), providers.name FROM domains \n\tINNER JOIN \n\t  providers on providers.id = domains.provider_id\n  WHERE \n\t-- DAY 1 OF THIS MONTH\n\t\texpiration_date >= CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 as TEXT)\n\tAND \n\t-- DAY 1 OF NEXT MONTH\n\t\texpiration_date < CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 + INTERVAL '1 month' as DATE) as TEXT)\n\nGROUP BY providers.name"
    }
   ]
  },
  {
   "title": "Nome dos domínios que expiram no próximo mês",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT domains.name, domains.expiration_date, providers.name as Provedor FROM domains \n\nINNER JOIN \n  providers on providers.id = domains.provider_id\n\nWHERE \n\t-- DAY 1 OF THIS MONTH\n\t\texpiration_date >= CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 as TEXT)\n\tAND \n\t-- DAY 1 OF NEXT MONTH\n\t\texpiration_date < CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 + INTERVAL '1 month' as DATE) as TEXT)\n\t\t\n\tORDER BY expiration_date"
    }
   ]
  },
  {
   "title": "Domínios que expiram no próximo mês",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM domains WHERE \n\t-- DAY 1 OF NEXT MONTH\n\t\texpiration_date >= CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 + INTERVAL '1 month' as DATE) as TEXT)\n\tAND \n\t-- DAY 1 OF NEXT+NEXT MONTH\n\t\texpiration_date < CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 + INTERVAL '2 month' as DATE) as TEXT)"
    }
   ]
  },
  {
   "title": "Domínios que expiram no próximo mês (por fornecedor)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*), providers.name FROM domains \n\tINNER JOIN \n\t  providers on providers.id = domains.provider_id\n  WHERE \n  \t-- DAY 1 OF NEXT MONTH\n  \t\texpiration_date >= CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 + INTERVAL '1 month' as DATE) as TEXT)\n  \tAND \n  \t-- DAY 1 OF NEXT+NEXT MONTH\n  \t\texpiration_date < CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 + INTERVAL '2 month' as DATE) as TEXT)\n\nGROUP BY providers.name"
    }
   ]
  },
  {
   "title": "Nome dos domínios que expiram no próximo mês",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT domains.name, domains.expiration_date, providers.name as Provedor FROM domains \n\nINNER JOIN \n  providers on providers.id = domains.provider_id\n\nWHERE \n  -- DAY 1 OF NEXT MONTH\n\t\texpiration_date >= CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 + INTERVAL '1 month' as DATE) as TEXT)\n\tAND \n\t-- DAY 1 OF NEXT+NEXT MONTH\n\t\texpiration_date < CAST(CAST(CURRENT_DATE - CAST(extract(day from current_date) as integer) + 1 + INTERVAL '2 month' as DATE) as TEXT)\n\t\t\n\tORDER BY expiration_date"
    }
   ]
  },
  {
   "title": "Domínios que expiram dentro de 90 dias",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM domains WHERE \n\t-- TODAY\n\t\texpiration_date >= CAST(CURRENT_DATE as TEXT)\n\tAND \n\t-- 90 DAYS LATER\n\t\texpiration_date < CAST(CAST(CURRENT_DATE + INTERVAL '90 day' as DATE) as TEXT)"
    }
   ]
  },
  {
   "title": "Domínios que expiram no próximo mês (por fornecedor)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*), providers.name FROM domains \n\tINNER JOIN \n\t  providers on providers.id = domains.provider_id\n  WHERE \n\t-- TODAY\n\t\texpiration_date >= CAST(CURRENT_DATE as TEXT)\n\tAND \n\t-- 90 DAYS LATER\n\t\texpiration_date < CAST(CAST(CURRENT_DATE + INTERVAL '90 day' as DATE) as TEXT)\n\nGROUP BY providers.name"
    }
   ]
  },
  {
   "title": "Nome dos domínios que expiram dentro de 90 dias",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT domains.name, domains.expiration_date, providers.name as Provedor FROM domains \n\nINNER JOIN \n  providers on providers.id = domains.provider_id\n\nWHERE \n\t-- TODAY\n\t\texpiration_date >= CAST(CURRENT_DATE as TEXT)\n\tAND \n\t-- 90 DAYS LATER\n\t\texpiration_date < CAST(CAST(CURRENT_DATE + INTERVAL '90 day' as DATE) as TEXT)\t\t\n\tORDER BY expiration_date"
    }
   ]
  },
  {
   "title": "Quantidade de Domínios que irão expirar por data",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT expiration_date, count(*) FROM domains WHERE expiration_date IS NOT NULL GROUP BY expiration_date ORDER BY expiration_date"
    }
   ]
  },
  { "title": "Contatos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Administradores",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT name, email FROM admins\n"
    }
   ]
  },
  {
   "title": "Registrantes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT name, email FROM registrants\n"
    }
   ]
  },
  {
   "title": "Techs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT name, email FROM techs\n"
    }
   ]
  },
  {
   "title": "Provedores",
   "type": "table",
   "description": "Registrars",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT name, email FROM registrars\n"
    }
   ]
  },
  {
   "title": "Domínios que precisam de monitoramento manual por não serem suportados ou inválidos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true
  },
  {
   "title": "Nome dos domínios não suportados ou inválidos",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT domains.name as UNSUPORTEDS, providers.name as provider FROM domains \nINNER JOIN \n  providers on providers.id = domains.provider_id\n  \nWHERE domains.name LIKE '%UNSUPORTED%'"
    },
    {
     "rawSql": "SELECT domains.name as INVALIDS, providers.name as provider FROM domains \nINNER JOIN \n  providers on providers.id = domains.provider_id\nWHERE domains.name LIKE '%INVALID%'"
    },
    {
     "rawSql": "SELECT name as All FROM domains WHERE name LIKE '%UNSUPORTED%' OR name LIKE '%INVALID%'"
    }
   ]
  }
 ]
}